image: alpine/edge
packages:
- nodejs
- npm
secrets:
- 7e6c4383-99ec-4063-bb75-04e5afad30d0

sources:
- git@git.sr.ht:~nicolaskempf57/vue-toaster

tasks:
- build: |
    cd ~/vue-toaster
    node --version
    npm --version
    npm ci
    npm run build
- publish: |
    cd ~/vue-toaster
    set +x
    echo //registry.npmjs.org/:_auth=$(< ~/NPM_TOKEN) >> .npmrc
    echo //registry.npmjs.org/:_authToken=$(< ~/NPM_TOKEN) >> .npmrc
    echo email=nicolas@conciergerie.dev >> .npmrc
    echo always-auth=true >> .npmrc
    echo scope=conciergerie-dev >> .npmrc
    set -x
    npm version --allow-same-version $(npm view @conciergerie-dev/vue-toaster@latest version)
    npm version --no-git-tag-version prerelease
    npm publish